name: present
description: A package to create presentations with.
version: 0.0.1-nullsafety.0
author: Wim07101993
homepage: https://github.com/wim07101993/present

environment:
  sdk: ">=2.12.0-259.8.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  carousel_slider: ^4.0.0-nullsafety.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

